package DIU_system;
import java.awt.*;
import simView.*;

// 소프트웨어공학 DIU 과제
// 12161569 컴퓨터공학과 박도윤

public class gpt extends ViewableDigraph
{

	public gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new genr("genr", 10);
		ViewableAtomic p = new DIU("DIU", 10);
		
		ViewableAtomic a1 = new AMI("ami_1", 10);
		ViewableAtomic a2 = new AMI("ami_2", 10);
		ViewableAtomic a3 = new AMI("ami_3", 10);
		ViewableAtomic a4 = new AMI("ami_4", 10);
		ViewableAtomic a5 = new AMI("ami_5", 10);
		ViewableAtomic a6 = new AMI("ami_6", 10);
		
		
		add(g);
		add(p);
		
		add(a1);
		add(a2);
		add(a3);
		add(a4);
		add(a5);
		add(a6);
		
  
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
		
		addCoupling(p, "out_ami_company", a1, "in");
		addCoupling(p, "out_ami_house", a2, "in");
		addCoupling(p, "out_ami_school", a3, "in");
		addCoupling(p, "out_ami_yh1", a4, "in");
		addCoupling(p, "out_ami_yh2", a5, "in");
		addCoupling(p, "out_ami_yh3", a6, "in");
		
		addCoupling(p, "re_request", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(30, 239));
        ((ViewableComponent)withName("DIU")).setPreferredLocation(new Point(236, 239));
        
        ((ViewableComponent)withName("ami_1")).setPreferredLocation(new Point(633, 82));
        ((ViewableComponent)withName("ami_3")).setPreferredLocation(new Point(632, 245));
        ((ViewableComponent)withName("ami_6")).setPreferredLocation(new Point(631, 486));
        ((ViewableComponent)withName("ami_2")).setPreferredLocation(new Point(632, 164));
        ((ViewableComponent)withName("ami_4")).setPreferredLocation(new Point(631, 327));
        ((ViewableComponent)withName("ami_5")).setPreferredLocation(new Point(631, 408));    
    }
}
