package DIU_system3;
import java.awt.*;
import simView.*;

// 소프트웨어공학 DIU 과제
// 12161569 컴퓨터공학과 박도윤

public class gpt extends ViewableDigraph
{

	public gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new genr("genr", 13);
		ViewableAtomic p = new DIU("DIU", 13);
		
		ViewableAtomic a1 = new AMI("ami_1", 10);
		ViewableAtomic a2 = new AMI("ami_2", 10);
		ViewableAtomic a3 = new AMI("ami_3", 10);
		ViewableAtomic a4 = new AMI("ami_4", 10);
		ViewableAtomic a5 = new AMI("ami_5", 10);
		ViewableAtomic a6 = new AMI("ami_6", 10);
		
		ViewableAtomic send_cnt = new send_cnt("send_cnt", 10);
		
		
		add(g);
		add(p);
		
		add(a1);
		add(a2);
		add(a3);
		add(a4);
		add(a5);
		add(a6);
		
		add(send_cnt);
		
  
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
		
		addCoupling(p, "out_ami_company", a1, "in");
		addCoupling(p, "out_ami_house", a2, "in");
		addCoupling(p, "out_ami_school", a3, "in");
		addCoupling(p, "out_ami_yh1", a4, "in");
		addCoupling(p, "out_ami_yh2", a5, "in");
		addCoupling(p, "out_ami_yh3", a6, "in");
		
		addCoupling(p, "re_request", g, "in");
		
		addCoupling(a1, "out", p, "in"); // company ami
		
		addCoupling(send_cnt, "out", p, "in");
		addCoupling(p, "send_check", send_cnt, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("ami_3")).setPreferredLocation(new Point(425, 239));
        ((ViewableComponent)withName("ami_1")).setPreferredLocation(new Point(420, 79));
        ((ViewableComponent)withName("ami_2")).setPreferredLocation(new Point(426, 157));
        ((ViewableComponent)withName("ami_5")).setPreferredLocation(new Point(427, 383));
        ((ViewableComponent)withName("ami_4")).setPreferredLocation(new Point(426, 313));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(1, 272));
        ((ViewableComponent)withName("ami_6")).setPreferredLocation(new Point(426, 459));        
        ((ViewableComponent)withName("send_cnt")).setPreferredLocation(new Point(127, 447));
        ((ViewableComponent)withName("DIU")).setPreferredLocation(new Point(155, 248));
    }
}
